# Codecov Configuration
# Documentation: https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error

    patch:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "_site/**/*"
  - "dist/**/*"
  - "coverage/**/*"
  - "htmlcov/**/*"
  - "node_modules/**/*"
  - "**/*.config.ts"
  - "**/*.config.js"
  - "scripts/**/*"
  - ".github/**/*"
