#!/bin/bash
# Generate Lighthouse PR comment with scores and report links
# Usage: generate-lighthouse-comment.sh
# Environment variables:
#   - GITHUB_RUN_ID: GitHub Actions run ID for artifact links
#   - GITHUB_SHA: Current commit SHA
# Reads from .lighthouse directory and extracts metrics

set -euo pipefail

# Get run ID from environment or GitHub context
RUN_ID="${GITHUB_RUN_ID:=unknown}"
COMMIT_SHA="${GITHUB_SHA:=unknown}"

# Initialize comment
{
  echo "## 📊 Lighthouse CI Performance Report"
  echo ""

  # Check if lighthouse results exist
  if [ -d ".lighthouse" ] && [ -n "$(ls -A .lighthouse 2>/dev/null)" ]; then
    # Find and parse the most recent Lighthouse JSON report
    LATEST_REPORT=$(find .lighthouse -name "*.json" -type f | sort -r | head -1)
    
    if [ -n "$LATEST_REPORT" ]; then
      # Extract scores using jq if available
      if command -v jq &> /dev/null; then
        PERFORMANCE=$(jq '.categories.performance.score * 100 | round' "$LATEST_REPORT" 2>/dev/null || echo "N/A")
        ACCESSIBILITY=$(jq '.categories.accessibility.score * 100 | round' "$LATEST_REPORT" 2>/dev/null || echo "N/A")
        BEST_PRACTICES=$(jq '.categories["best-practices"].score * 100 | round' "$LATEST_REPORT" 2>/dev/null || echo "N/A")
        SEO=$(jq '.categories.seo.score * 100 | round' "$LATEST_REPORT" 2>/dev/null || echo "N/A")
      else
        PERFORMANCE="N/A"
        ACCESSIBILITY="N/A"
        BEST_PRACTICES="N/A"
        SEO="N/A"
      fi

      # Create score badges with color coding
      format_score() {
        local score=$1
        if [ "$score" != "N/A" ]; then
          if [ "$score" -ge 90 ]; then
            echo "🟢 $score"
          elif [ "$score" -ge 80 ]; then
            echo "🟡 $score"
          else
            echo "🔴 $score"
          fi
        else
          echo "⚪ $score"
        fi
      }

      echo "### ✅ Status: Performance Analysis Complete"
      echo ""
      echo "**Build:** ✅ Lighthouse CI passed"
      echo ""
      echo "### 📈 Performance Scores"
      echo ""
      echo "| Category | Score |"
      echo "|----------|-------|"
      echo "| Performance | $(format_score "$PERFORMANCE") |"
      echo "| Accessibility | $(format_score "$ACCESSIBILITY") |"
      echo "| Best Practices | $(format_score "$BEST_PRACTICES") |"
      echo "| SEO | $(format_score "$SEO") |"
      echo ""
      
      echo "### 📋 Detailed Reports"
      echo ""
      if [ "$RUN_ID" != "unknown" ]; then
        echo "**Direct Links:**"
        echo "- 🔗 [📊 HTML Lighthouse Reports](https://github.com/$GITHUB_REPOSITORY/actions/runs/$RUN_ID/artifacts)"
        echo ""
        echo "**Download Instructions:**"
        echo "1. Go to the [Actions tab](https://github.com/$GITHUB_REPOSITORY/actions)"
        echo "2. Find this workflow run (commit: \`${COMMIT_SHA:0:7}\`)"
        echo "3. Download the \"lighthouse-reports\" artifact"
        echo "4. Extract and open the HTML files in your browser"
      else
        echo "- Check the workflow artifacts for detailed Lighthouse reports"
      fi
      echo ""
    else
      echo "✅ Lighthouse CI analysis completed successfully."
      echo ""
      if [ "$RUN_ID" != "unknown" ]; then
        echo "📋 [View Detailed Reports](https://github.com/$GITHUB_REPOSITORY/actions/runs/$RUN_ID/artifacts)"
      fi
    fi
  else
    echo "⚠️ No Lighthouse results found. Check workflow logs for details."
  fi

  echo ""
  echo "---"
  echo "*Generated by Lighthouse CI* | [View workflow run](https://github.com/$GITHUB_REPOSITORY/actions/runs/$RUN_ID)"
} > lighthouse-comment.md
