#!/bin/bash
# Generate Playwright E2E PR comment with test results and report links
# Usage: generate-playwright-comment.sh
# Environment variables:
#   - GITHUB_RUN_ID: GitHub Actions run ID for artifact links
#   - GITHUB_SHA: Current commit SHA
#   - GITHUB_REPOSITORY: GitHub repository (owner/repo)
# Reads from playwright-report directory and extracts test results

set -euo pipefail

# Get run ID from environment or GitHub context
RUN_ID="${GITHUB_RUN_ID:=unknown}"
COMMIT_SHA="${GITHUB_SHA:=unknown}"
REPO="${GITHUB_REPOSITORY:=unknown}"

# Initialize comment
{
  echo "## 🎭 Playwright E2E Test Report"
  echo ""

  # Check if playwright report exists
  if [ -d "playwright-report" ] && [ -n "$(ls -A playwright-report 2>/dev/null)" ]; then
    # Try to extract test results from playwright report
    if [ -f "playwright-report/index.html" ]; then
      # Parse basic test statistics from the HTML report if possible
      # This is a simple approach - could be enhanced with JSON results
      
      echo "### ✅ Test Execution Completed"
      echo ""
      
      # Check if test-results directory exists for additional info
      if [ -d "test-results" ]; then
        FAILURE_COUNT=$(find test-results -name "*.png" -o -name "*.webm" 2>/dev/null | wc -l | tr -d ' ')
        if [ "$FAILURE_COUNT" -gt 0 ]; then
          echo "⚠️ **Test artifacts found**: $FAILURE_COUNT failure screenshots/videos captured"
          echo ""
        fi
      fi
      
      echo "### 📋 View Full Reports"
      echo ""
      
      if [ "$REPO" != "unknown" ]; then
        echo "**Public Report (after merge to main):**"
        echo "- 🔗 [📊 View Playwright HTML Report](https://turbocoder13.github.io/bulma-turbo-themes/playwright/)"
        echo ""
        echo "**Or download from artifacts:**"
        echo "- 📥 [Download Playwright Report](https://github.com/$REPO/actions/runs/$RUN_ID/artifacts)"
        if [ -d "test-results" ]; then
          echo "- 📥 [Download Test Results (screenshots/videos)](https://github.com/$REPO/actions/runs/$RUN_ID/artifacts)"
        fi
      else
        echo "**Local Development:**"
        echo "- 🔗 [View Report](http://localhost:4000/playwright/)"
        echo "- 🔗 [Standalone server](http://localhost:9323) (run \`./scripts/local/serve-reports.sh\`)"
        echo ""
        echo "**Note:** If Jekyll server is running, the report is already available."
      fi
      echo ""
      
    else
      echo "⚠️ No Playwright HTML report found, but report directory exists."
      echo ""
    fi
  else
    echo "⚠️ No Playwright results found. Check workflow logs for details."
    echo ""
    if [ "$REPO" != "unknown" ]; then
      echo "- 📥 [View workflow run](https://github.com/$REPO/actions/runs/$RUN_ID)"
    fi
  fi

  echo ""
  echo "---"
  if [ "$RUN_ID" != "unknown" ]; then
    echo "*Generated by Playwright E2E Tests* | [View workflow run](https://github.com/$REPO/actions/runs/$RUN_ID)"
  else
    echo "*Generated by Playwright E2E Tests (Local)*"
  fi
  echo ""
  echo "<!-- playwright-e2e-comment -->"
} > playwright-comment.md

