#!/bin/bash
# Generate Lighthouse PR comment with scores and report links
# Usage: generate-lighthouse-comment.sh
# Reads from .lighthouse directory and extracts metrics

set -euo pipefail

# Initialize comment
{
  echo "## 📊 Lighthouse CI Report"
  echo ""
  echo "Lighthouse performance analysis completed."
  echo ""

  # Check if lighthouse results exist
  if [ -d ".lighthouse" ] && [ -n "$(ls -A .lighthouse 2>/dev/null)" ]; then
    echo "### Results"
    echo ""

    # Find and parse the most recent Lighthouse JSON report
    LATEST_REPORT=$(find .lighthouse -name "*.json" -type f | sort -r | head -1)
    
    if [ -n "$LATEST_REPORT" ]; then
      # Extract scores using jq if available, otherwise use grep/sed
      if command -v jq &> /dev/null; then
        PERFORMANCE=$(jq '.categories.performance.score * 100 | round' "$LATEST_REPORT" 2>/dev/null || echo "N/A")
        ACCESSIBILITY=$(jq '.categories.accessibility.score * 100 | round' "$LATEST_REPORT" 2>/dev/null || echo "N/A")
        BEST_PRACTICES=$(jq '.categories["best-practices"].score * 100 | round' "$LATEST_REPORT" 2>/dev/null || echo "N/A")
        SEO=$(jq '.categories.seo.score * 100 | round' "$LATEST_REPORT" 2>/dev/null || echo "N/A")
        REPORT_URL=$(jq -r '.lighthouseVersion' "$LATEST_REPORT" 2>/dev/null || echo "")
      else
        PERFORMANCE="N/A"
        ACCESSIBILITY="N/A"
        BEST_PRACTICES="N/A"
        SEO="N/A"
      fi

      # Create score badges
      format_score() {
        local score=$1
        if [ "$score" != "N/A" ]; then
          if [ "$score" -ge 90 ]; then
            echo "🟢 $score"
          elif [ "$score" -ge 80 ]; then
            echo "🟡 $score"
          else
            echo "🔴 $score"
          fi
        else
          echo "⚪ $score"
        fi
      }

      echo "| Category | Score |"
      echo "|----------|-------|"
      echo "| Performance | $(format_score "$PERFORMANCE") |"
      echo "| Accessibility | $(format_score "$ACCESSIBILITY") |"
      echo "| Best Practices | $(format_score "$BEST_PRACTICES") |"
      echo "| SEO | $(format_score "$SEO") |"
      echo ""
      echo "✅ Lighthouse CI analysis completed successfully."
      echo ""
      echo "📋 **Report Details:**"
      echo "- Check the workflow artifacts for detailed Lighthouse reports"
      echo "- Reports are available in the \"lighthouse-reports\" artifact"
    else
      echo "✅ Lighthouse CI analysis completed."
      echo ""
      echo "📋 Check the workflow artifacts for detailed Lighthouse reports."
    fi
  else
    echo "⚠️ No Lighthouse results found. Check workflow logs for details."
  fi

  echo ""
  echo "---"
  echo "*Generated by Lighthouse CI*"
} > lighthouse-comment.md
