---
name: Setup Environment
description: Set up Bun, Node.js, and Ruby with caching and install dependencies

inputs:
  bun-version:
    description: 'Bun version to use'
    required: false
    default: '1.1.8'
  node-version:
    description: 'Node.js version to use (for compatibility)'
    required: false
    default: '22'
  ruby-version:
    description: 'Ruby version to use'
    required: false
    default: '3.3.9'
  skip-ruby:
    description: 'Skip Ruby setup (for Node.js-only workflows)'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Verify Bun installation
      shell: bash
      run: |
        echo "Bun version: $(bun --version)"

    - name: Setup Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        node-version: ${{ inputs.node-version }}
        # Note: Bun handles caching, but Node.js is needed for npm publish compatibility

    - name: Verify Node.js version
      shell: bash
      run: ./scripts/ci/verify-node-version.sh "${{ inputs.node-version }}"

    - name: Setup Ruby
      if: inputs.skip-ruby != 'true'
      uses: ruby/setup-ruby@d5126b9b3579e429dd52e51e68624dda2e05be25 # v1.267.0
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler: '2.3.26'
        bundler-cache: true

    - name: Verify Ruby and Bundler setup
      if: inputs.skip-ruby != 'true'
      shell: bash
      run: ./scripts/ci/verify-ruby-setup.sh

    - name: Install Ruby dependencies
      if: inputs.skip-ruby != 'true'
      shell: bash
      run: ./scripts/ci/install-ruby-deps.sh

    - name: Install uv
      uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2
      with:
        enable-cache: true

    - name: Install Python via uv
      shell: bash
      run: ./scripts/ci/setup-python-uv.sh

    - name: Install CI dependencies
      shell: bash
      run: ./scripts/ci/install-ci-deps.sh

    - name: Cache Bun dependencies
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          ~/.bun/install/cache
          node_modules
        key: bun-${{ runner.os }}-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          bun-${{ runner.os }}-

    - name: Install Node.js dependencies with Bun
      shell: bash
      run: ./scripts/ci/bun-install-with-retry.sh
