---
name: Setup Environment
description: Set up Node.js and Ruby with caching and install dependencies

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22'
  ruby-version:
    description: 'Ruby version to use'
    required: false
    default: '3.3.9'
  skip-ruby:
    description: 'Skip Ruby setup (for Node.js-only workflows)'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm

    - name: Verify Node.js version
      shell: bash
      run: ./scripts/ci/verify-node-version.sh "${{ inputs.node-version }}"

    - name: Setup Ruby
      if: inputs.skip-ruby != 'true'
      uses: ruby/setup-ruby@d5126b9b3579e429dd52e51e68624dda2e05be25 # v1.267.0
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler: '2.3.26'
        bundler-cache: true

    - name: Verify Ruby and Bundler setup
      if: inputs.skip-ruby != 'true'
      shell: bash
      run: ./scripts/ci/verify-ruby-setup.sh

    - name: Install Ruby dependencies
      if: inputs.skip-ruby != 'true'
      shell: bash
      run: ./scripts/ci/install-ruby-deps.sh

    - name: Install uv
      uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
      with:
        enable-cache: true

    - name: Install Python via uv
      shell: bash
      run: ./scripts/ci/setup-python-uv.sh

    - name: Install CI dependencies
      shell: bash
      run: ./scripts/ci/install-ci-deps.sh

    - name: Install Node.js dependencies
      shell: bash
      run: npm ci
