---
name: Setup Environment
description: Set up Bun, Node.js, and Ruby with caching and install dependencies

inputs:
  bun-version:
    description: 'Bun version to use'
    required: false
    default: '1.1.8'
  node-version:
    description: 'Node.js version to use (for compatibility)'
    required: false
    default: '22'
  ruby-version:
    description: 'Ruby version to use'
    required: false
    default: '3.3.9'
  skip-ruby:
    description: 'Skip Ruby setup (for Node.js-only workflows)'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@b7a1c7ccf290d58743029c4f6903da283811b979 # v2.1.0
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Verify Bun installation
      shell: bash
      run: |
        echo "Bun version: $(bun --version)"

    - name: Setup Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
      with:
        node-version: ${{ inputs.node-version }}
        # Note: Bun handles caching, but Node.js is needed for npm publish compatibility

    - name: Verify Node.js version
      shell: bash
      run: ./scripts/ci/verify-node-version.sh "${{ inputs.node-version }}"

    - name: Setup Ruby
      if: inputs.skip-ruby != 'true'
      uses: ruby/setup-ruby@b90be12699fdfcbee4440c2bba85f6f460446bb0 # v1.279.0
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler: '2.3.26'
        bundler-cache: true

    - name: Verify Ruby and Bundler setup
      if: inputs.skip-ruby != 'true'
      shell: bash
      run: ./scripts/ci/verify-ruby-setup.sh

    - name: Install Ruby dependencies
      if: inputs.skip-ruby != 'true'
      shell: bash
      run: ./scripts/ci/install-ruby-deps.sh

    - name: Install uv
      uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
      with:
        enable-cache: true

    - name: Install Python via uv
      shell: bash
      run: ./scripts/ci/setup-python-uv.sh

    - name: Install CI dependencies
      shell: bash
      run: ./scripts/ci/install-ci-deps.sh

    - name: Cache Bun dependencies
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: |
          ~/.bun/install/cache
          node_modules
        key: bun-${{ runner.os }}-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          bun-${{ runner.os }}-

    - name: Install Node.js dependencies with Bun
      shell: bash
      run: ./scripts/ci/bun-install-with-retry.sh
