---
name: Setup Environment
description: Set up Bun, Node.js, and Ruby with caching and install dependencies

inputs:
  bun-version:
    description: 'Bun version to use'
    required: false
    default: '1.3.5'
  node-version:
    description: 'Node.js version to use (for compatibility)'
    required: false
    default: '22'
  ruby-version:
    description: 'Ruby version to use'
    required: false
    default: '3.4.7'
  skip-ruby:
    description: 'Skip Ruby setup (for Node.js-only workflows)'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2.1.2
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Verify Bun installation
      shell: bash
      run: |
        echo "Bun version: $(bun --version)"

    - name: Setup Node.js
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
      with:
        node-version: ${{ inputs.node-version }}
        # Note: Bun handles caching, but Node.js is needed for npm publish compatibility

    - name: Verify Node.js version
      shell: bash
      run: ./scripts/ci/verify-node-version.sh "${{ inputs.node-version }}"

    - name: Setup Ruby
      if: inputs.skip-ruby != 'true'
      uses: ruby/setup-ruby@8d27f39a5e7ad39aebbcbd1324f7af020229645c # v1.287.0
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true

    - name: Verify Ruby and Bundler setup
      if: inputs.skip-ruby != 'true'
      shell: bash
      run: ./scripts/ci/verify-ruby-setup.sh

    - name: Install Ruby dependencies
      if: inputs.skip-ruby != 'true'
      shell: bash
      run: ./scripts/ci/install-ruby-deps.sh

    - name: Install uv
      uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0
      with:
        enable-cache: true

    - name: Install Python via uv
      shell: bash
      run: ./scripts/ci/setup-python-uv.sh

    - name: Install CI dependencies
      shell: bash
      run: ./scripts/ci/install-ci-deps.sh

    - name: Cache Bun dependencies
      uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        path: |
          ~/.bun/install/cache
          node_modules
        key: bun-${{ runner.os }}-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          bun-${{ runner.os }}-

    - name: Install Node.js dependencies with Bun
      shell: bash
      run: ./scripts/ci/bun-install-with-retry.sh
