---
name: Setup Bun
description: Install and configure Bun JavaScript runtime with caching

inputs:
  bun-version:
    description: 'Bun version to install'
    required: false
    default: 'latest'
  frozen-lockfile:
    description: 'Use frozen lockfile (fail if lockfile needs update)'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@b7a1c7ccf290d58743029c4f6903da283811b979 # v2.1.0
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Verify Bun installation
      shell: bash
      run: |
        echo "Bun version: $(bun --version)"
        echo "Bun path: $(which bun)"

    - name: Install dependencies with Bun
      shell: bash
      run: |
        if [ "${{ inputs.frozen-lockfile }}" = "true" ]; then
          bun install --frozen-lockfile
        else
          bun install
        fi
